<?php
/**
 */

namespace execut\settings\crudFields\detailViewField\addon;


use execut\crudFields\fields\detailViewField\addon\Help;

class HelpFromSetting extends Help
{
    protected $key = null;

    /**
     * @param null $key
     */
    public function setKey($key): void
    {
        $this->key = $key;
    }

    /**
     * @return null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }
}