<?php
/**
 */

namespace execut\settings\controllers;


use execut\crud\params\Crud;
use execut\settings\models\Setting;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotAcceptableHttpException;

class BackendController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [$this->module->adminRole],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id === 'update' || $action->id === 'delete') {
            $id = \yii::$app->request->getQueryParam('id');
            $id = (int) $id;
            if (!$this->module->checkHasAccessToSetting($id)) {
                throw new NotAcceptableHttpException('Доступ к записи запрещён');
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $configurator = new Crud([
            'modelClass' => Setting::class,
            'modelName' => Setting::MODEL_NAME,
        ]);

        return $configurator->actions();
    }
}