<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace execut\settings\models\base;

use Yii;

/**
 * This is the base-model class for table "settings_settings".
 *
 * @property integer $id
 * @property string $name
 * @property string $key
 * @property string $value
 * @property string $aliasModel
 */
abstract class Setting extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'settings_settings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'key', 'value'], 'required'],
            [['name', 'key', 'value'], 'string', 'max' => 255],
            [['key'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('execut/settings', 'ID'),
            'name' => Yii::t('execut/settings', 'Name'),
            'key' => Yii::t('execut/settings', 'Key'),
            'value' => Yii::t('execut/settings', 'Value'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \execut\settings\models\queries\SettingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \execut\settings\models\queries\SettingQuery(get_called_class());
    }


}
